"""removed email and phone columns

Revision ID: b8169fa39192
Revises: d9bce4642c5d
Create Date: 2024-07-14 12:04:58.136524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8169fa39192'
down_revision = 'd9bce4642c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=15), nullable=True))

    # ### end Alembic commands ###
